# Generated by Django 2.2.9 on 2021-11-10 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20211110_1912'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['pub_date']},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='order_date',
            new_name='pub_date',
        ),
    ]
